# Generated by Django 5.0.2 on 2025-12-01 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_sistema_escolar_api", "0003_alumnos_maestros"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoAcademico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conferencia", "Conferencia"),
                            ("taller", "Taller"),
                            ("seminario", "Seminario"),
                            ("concurso", "Concurso"),
                            ("curso", "Curso"),
                            ("congreso", "Congreso"),
                            ("simposio", "Simposio"),
                            ("foro", "Foro"),
                            ("panel", "Panel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("lugar", models.CharField(max_length=200)),
                (
                    "publico_objetivo",
                    models.CharField(
                        choices=[
                            ("estudiantes", "Estudiantes"),
                            ("profesores", "Profesores"),
                            ("publico_general", "Público General"),
                            ("investigadores", "Investigadores"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "programa_educativo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ingenieria_sistemas", "Ingeniería en Sistemas"),
                            ("ingenieria_industrial", "Ingeniería Industrial"),
                            ("administracion", "Administración"),
                            ("contaduria", "Contaduría"),
                            ("derecho", "Derecho"),
                            ("psicologia", "Psicología"),
                            ("todos", "Todos los programas"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("descripcion", models.TextField(max_length=300)),
                ("cupo_maximo", models.IntegerField()),
                ("creation", models.DateTimeField(auto_now_add=True, null=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Académico",
                "verbose_name_plural": "Eventos Académicos",
                "ordering": ["-fecha", "-hora_inicio"],
            },
        ),
    ]
