# Generated by Django 5.0.2 on 2025-12-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_sistema_escolar_api", "0004_eventoacademico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoacademico",
            name="publico_objetivo",
            field=models.CharField(
                choices=[
                    ("estudiantes", "Estudiantes"),
                    ("profesores", "Profesores"),
                    ("publico_general", "Público General"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventoacademico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("conferencia", "Conferencia"),
                    ("taller", "Taller"),
                    ("seminario", "Seminario"),
                    ("concurso", "Concurso"),
                ],
                max_length=20,
            ),
        ),
    ]
