# Generated by Django 5.0.2 on 2025-12-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dev_sistema_escolar_api",
            "0005_alter_eventoacademico_publico_objetivo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoacademico",
            name="programa_educativo",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "ingenieria_ciencias_computacion",
                        "Ingeniería en Ciencias de la Computación",
                    ),
                    (
                        "licenciatura_ciencias_computacion",
                        "Licenciatura en Ciencias de la Computación",
                    ),
                    (
                        "ingenieria_tecnologias_informacion",
                        "Ingeniería en Tecnologías de la Información",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
