# Generated by Django 5.0.2 on 2025-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_sistema_escolar_api", "0006_alter_eventoacademico_programa_educativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="administradores",
            name="fecha_nacimiento",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
